package dev.aiaerial.signal.data.export

import dev.aiaerial.signal.data.alert.Alert
import dev.aiaerial.signal.data.alert.AlertSeverity
import dev.aiaerial.signal.data.model.ApAssociation
import dev.aiaerial.signal.data.model.EventType
import dev.aiaerial.signal.data.model.NetworkEvent
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Generates structured Markdown session reports suitable for sharing,
 * later PDF rendering, or AI summarization.
 */
object SessionReportBuilder {

    private val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.US)

    fun buildMarkdownReport(
        sessionId: String,
        events: List<NetworkEvent>,
        alerts: List<Alert> = emptyList(),
        aiSummary: String? = null,
    ): String = buildString {
        val sorted = events.sortedBy { it.timestamp }
        val startTime = sorted.firstOrNull()?.timestamp
        val endTime = sorted.lastOrNull()?.timestamp

        // Header
        appendLine("# SIGNAL Session Report")
        appendLine()
        appendLine("**Generated:** ${dateFormat.format(Date())}")
        appendLine("**Session:** `$sessionId`")
        if (startTime != null && endTime != null) {
            appendLine("**Start:** ${dateFormat.format(Date(startTime))}")
            appendLine("**End:** ${dateFormat.format(Date(endTime))}")
            val durationMin = (endTime - startTime) / 60_000
            appendLine("**Duration:** ${durationMin}m")
        }
        appendLine("**Total events:** ${events.size}")
        appendLine()

        // Event type breakdown
        appendLine("## Event Summary")
        appendLine()
        appendLine("| Type | Count |")
        appendLine("|------|-------|")
        events.groupBy { it.eventType }
            .entries
            .sortedByDescending { it.value.size }
            .forEach { (type, evts) ->
                appendLine("| ${type.name} | ${evts.size} |")
            }
        appendLine()

        // Client summary
        val clients = events.mapNotNull { it.clientMac }.distinct()
        if (clients.isNotEmpty()) {
            appendLine("## Clients (${clients.size})")
            appendLine()
            for (mac in clients) {
                val clientEvents = events.filter { it.clientMac == mac }
                val roams = clientEvents.count { it.eventType == EventType.ROAM }
                val deauths = clientEvents.count { it.eventType == EventType.DEAUTH || it.eventType == EventType.DISASSOC }
                val rssiValues = clientEvents.mapNotNull { it.rssi }
                val rssiRange = if (rssiValues.isNotEmpty()) "${rssiValues.min()} to ${rssiValues.max()} dBm" else "N/A"
                appendLine("- `$mac`: ${clientEvents.size} events, $roams roams, $deauths disconnects, RSSI $rssiRange")
            }
            appendLine()
        }

        // AP summary
        val aps = events.mapNotNull { it.apName }.distinct()
        if (aps.isNotEmpty()) {
            appendLine("## Access Points (${aps.size})")
            appendLine()
            appendLine("| AP | Events | Clients |")
            appendLine("|----|--------|---------|")
            for (ap in aps) {
                val apEvents = events.filter { it.apName == ap }
                val apClients = apEvents.mapNotNull { it.clientMac }.distinct().size
                appendLine("| $ap | ${apEvents.size} | $apClients |")
            }
            appendLine()
        }

        // Alerts
        if (alerts.isNotEmpty()) {
            appendLine("## Alerts (${alerts.size})")
            appendLine()
            for (alert in alerts.sortedBy { it.severity }) {
                val icon = when (alert.severity) {
                    AlertSeverity.CRITICAL -> "[CRITICAL]"
                    AlertSeverity.WARNING -> "[WARNING]"
                    AlertSeverity.INFO -> "[INFO]"
                }
                appendLine("- **$icon ${alert.title}**: ${alert.detail}")
            }
            appendLine()
        }

        // AI summary placeholder
        if (aiSummary != null) {
            appendLine("## AI Analysis")
            appendLine()
            appendLine(aiSummary)
            appendLine()
        } else {
            appendLine("## AI Analysis")
            appendLine()
            appendLine("*Not yet generated. Use SIGNAL's AI Triage to analyze events.*")
            appendLine()
        }

        // Footer
        appendLine("---")
        appendLine("*Report generated by SIGNAL v0.3.0 — AI Aerial Solutions*")
    }
}
